[package]
name = "ac-trainer"
version = "0.1.0"
authors = ["Spencer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
